app:

  port: 5000

  logLevel: Debug

  authServer:
    users:

      - johndoe:
          publicKeys:
            - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIArlhna9c5NLHKlDXkjpDNLUvw0Zj6cUTfTFELhKN7ek"

          image: alpine:3.21
          shellCommand: /bin/sh
          binds:
          networks:
